# Nombre del capitulo. {#intro}

All chapters start with a first-level heading followed by your chapter title, like the line above. There should be only one first-level heading (`#`) per .Rmd file.



## A section

## Otra seccion

All chapter sections start with a second-level (`##`) or higher heading followed by your section title, like the sections above and below here. You can have as many as you want within a chapter.

### A subsection {.unnumbered}

The subtopic

#### 

More subdivision

##### 

Even more subdivision

### An unnumbered section {.unnumbered}

Chapters and sections are numbered by default. To un-number a heading, add a `{.unnumbered}` or the shorter `{-}` at the end of the heading, like in this section.

Remember not to use only 1 *\#* as this indicates a new chapter

## NOTE the size of font changes with the number *\#*

### NOTE the size of font changes with the number *\#*

#### NOTE the size of font changes with the number *\#*

##### NOTE the size of font changes with the number *\#*

Don't miss Table \@ref(tab:nice-table).
