# Footnotes and citations 

## Footnotes

Footnotes are put inside the square brackets after a caret `^[]`. Like this one ^[This is a footnote.]. 


Let's add a second footnote. In this case we add information on the origin of matrix algebra ^[The term matrix was introduced by the 19th-century English mathematician James Sylvester, but it was his friend the mathematician Arthur Cayley who developed the algebraic aspect of matrices in two papers in the 1850s. ]

Mi tercer footnote es filosofico ^[kgjljgljhggjlhgjhgljgjhl]


## Citations

Reference items in your bibliography file(s) using `@key`.

For example, we are using the **bookdown** package [@R-bookdown] (check out the last code chunk in index.Rmd to see how this citation key was added) in this sample book, which was built on top of R Markdown and **knitr** [@xie2015] (this citation was added manually in an external file book.bib). 
Note that the `.bib` files need to be listed in the index.Rmd with the YAML `bibliography` key.


#### Here is second citation. 

Evolutionary processes in orchids are likely to be a interaction between natural selection and genetic drift [@tremblay2005variation]. 

#### Here is a third citation

un articulo de Damon excepcional [@damon2000review]

## Links to websites


The RStudio Visual Markdown Editor can also make it easier to insert citations: <https://rstudio.github.io/visual-markdown-editing/#/citations>

<https://www.researchgate.net/profile/Raymond-Tremblay>




