# Blocks

## Equations

Here is an equation.

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom) 
\end{equation} 

You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom). 

  -- this is the script to make the equation connectable in the text

** that the `....` are to make the text visual


## Theorems and proofs

Labeled theorems can be referenced in text using `\@ref(thm:tri)`, for example, check out this smart theorem \@ref(thm:tri).

::: {.theorem #tri}
For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$

A site to help create your equations $$\bar{x}=\frac{\sum x_{i}}{n}$$




<https://latex.codecogs.com/eqneditor/editor.php>


Ahora se enseña la formula del promedio \@ref(thm:promedio)

::: {.theorem #promedio}
$$\bar{x}= \frac{\sum x_{i}}{n}$$

Si quiere la ecuación en la linea usa solamente un "$" antes y despues de la formula. 
El promedio tiene la siguiente formula $\bar{x}= \frac{\sum x_{i}}{n}$ y la varianza se estima tomando la diferencia entre los valores y el promedio.    




:::

Read more here <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html>.

***

## Callout blocks


The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html
